a_eplatform_homepage:
    path:     /hello
    defaults: { _controller: AEplatformBundle:Default:index }

page_d_accueil:
    path:    /homepage
    defaults: {_controller: AEplatformBundle:Advert:homepage }

page_faq:
    path:   /faq
<<<<<<< HEAD
    defaults: {_controller: AEplatformBundle:Advert:faq}
=======
    defaults: {_controller: AEplatformBundle:Advert:faq}



>>>>>>> 886e0ee97acc4d643f97bb0b5f7bc8bc8ecbd63a
