a_eplatform_homepage:
    path:     /hello
    defaults: { _controller: AEplatformBundle:Default:index }

page_d_accueil:
    path:    /homepage
    defaults: {_controller: AEplatformBundle:Advert:homepage }

page_contact:
    path:   /pagecontact
    defaults: {_controller: AEplatformBundle:Advert:contact}
